### Central configuration for the module

# Camera settings
CAMERA_SOURCE = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
CAMERA_BUFFER_SIZE = 1

# YOLO26 
YOLO_MODEL = "yolo26m-pose.pt" 
CONFIDENCE_THRESHOLD = 0.5
HARDWARE_DETECTION_INTERVAL = 3

WASTE_DELAY_SECONDS = 5
